spring.application.name=class3
nominatim.base-url=https://nominatim.openstreetmap.org
nominatim.user-agent=class3-geocoding-app/1.0 (thiagobf.barbosa@gmail.com)
nominatim.email=thiagobf.barbosa@gmail.com
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:mysql://java-aws-class-database-1.cszuycoaawux.us-east-1.rds.amazonaws.com:3306/consulta_coordenada?useSSL=true&requireSSL=true&verifyServerCertificate=true&trustCertificateKeyStoreUrl=file:global-bundle.pem
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
