spring.application.name=class3
nominatim.base-url=https://nominatim.openstreetmap.org
nominatim.user-agent=class3-geocoding-app/1.0 (contato: dev@example.com)
springdoc.swagger-ui.path=/swagger-ui.html
